#!/bin/bash

# WARNING: this script only works with maven, please install it in your env

command_exists () {
    type "$1" &> /dev/null ;
}

if command_exists mvn ; then
  BASEDIR=$(dirname "$0")

  (
    cd $BASEDIR/../core/; mvn assembly:assembly
    cp target/searcher-0.0.1-jar-with-dependencies.jar ../prebuild/searcher.jar
  )
else
  echo 'Please install Maven to build this app.'
fi
