#!/bin/bash

BASEDIR=$(dirname "$0")

rm $BASEDIR/../vendor/*.jar
wget http://central.maven.org/maven2/com/google/guava/guava/19.0/guava-19.0.jar -O $BASEDIR/../vendor/guava-19.0.jar
wget http://central.maven.org/maven2/org/apache/lucene/lucene-core/6.0.0/lucene-core-6.0.0.jar -O $BASEDIR/../vendor/lucene-core-6.0.0.jar
wget http://central.maven.org/maven2/org/apache/lucene/lucene-analyzers-common/6.0.0/lucene-analyzers-common-6.0.0.jar -O $BASEDIR/../vendor/lucene-analyzers-common-6.0.0.jar
wget http://central.maven.org/maven2/org/apache/hadoop/hadoop-mapreduce-client-core/2.7.2/hadoop-mapreduce-client-core-2.7.2.jar -O $BASEDIR/../vendor/hadoop-mapreduce-client-core-2.7.2.jar
wget http://central.maven.org/maven2/org/apache/hadoop/hadoop-common/2.7.2/hadoop-common-2.7.2.jar -O $BASEDIR/../vendor/hadoop-common-2.7.2.jar
wget http://central.maven.org/maven2/org/apache/hadoop/hadoop-annotations/2.7.2/hadoop-annotations-2.7.2.jar -O $BASEDIR/../vendor/hadoop-annotations-2.7.2.jar

hdfs dfs -rm -f -r hw1/input/
hdfs dfs -mkdir -p hw1/input/
hdfs dfs -put /home/cp2016/shared/hw1/input hw1/input
